baseURL = "https://morgemoensch.github.io/Studentenvertretung-FFHS/"
languageCode = "de-ch"
publishDir = "docs"
title = "Studentenvertretung FFHS"
theme = "hugo-sugoi"
paginate = 5

[menu]
    [[menu.nav]]
	name = "about"
	url = "about"
